project:
  type: website
  output-dir: docs
  render:
    - apresentacao.qmd
    - landforms.qmd
    - elevation_range.qmd  
    - wetland_score.qmd
    - soil_diversity.qmd
    - Z_scores.qmd
    - landscape_heterogeneity.qmd
    - resilience.qmd
    

execute:   
  eval: false
  
website: 
  navbar:
    left:
      - text: Tutoriais
        menu:
         - text: Heterogeneidade da paisagem
         - text: Conectividade local
           href: https://resiliencia-climatica-brasil.github.io/Resistencia/
         
      - text: Downloads
        href: https://projeto-resiliencia-tnc.hub.arcgis.com        
  sidebar: 
    title: "Mapeamento de áreas resilientes a mudanças climáticas nos biomas brasileiros" 
    logo: figs/1667403883848_theme_logo.png     
    style: "docked"
    contents:
      - section: "Sumário"
        contents:
          - apresentacao.qmd
          - landforms.qmd
          - elevation_range.qmd   
          - wetland_score.qmd
          - soil_diversity.qmd
          - Z_scores.qmd
          - landscape_heterogeneity.qmd
          - resilience.qmd
          
              
  page-navigation: true
  favicon: figs/1667403883848_theme_logo.png
bibliography: bibliografia.bib
csl: citation_style.csl
lang: pt-br
format:
  html:
    theme: default
    css: styles.css   

